declare module "@mui/material/Typography" {
  interface TypographyPropsVariantOverrides {
    d1Regular: true;
    d1Medium: true;
    d1SemiBold: true;
    d1Bold: true;
    d2Regular: true;
    d2Medium: true;
    d2SemiBold: true;
    d2Bold: true;
    h1Regular: true;
    h1Medium: true;
    h1SemiBold: true;
    h1Bold: true;
    h1sRegular: true;
    h1sMedium: true;
    h1sSemiBold: true;
    h1sBold: true;
    h2Regular: true;
    h2Medium: true;
    h2SemiBold: true;
    h2Bold: true;
    h2sRegular: true;
    h2sMedium: true;
    h2sSemiBold: true;
    h2sBold: true;
    h3Regular: true;
    h3Medium: true;
    h3SemiBold: true;
    h3Bold: true;
    h3sRegular: true;
    h3sMedium: true;
    h3sSemiBold: true;
    h3sBold: true;
    h4Regular: true;
    h4Medium: true;
    h4SemiBold: true;
    h4Bold: true;
    h4sRegular: true;
    h4sMedium: true;
    h4sSemiBold: true;
    h4sBold: true;
    h5Regular: true;
    h5Medium: true;
    h5SemiBold: true;
    h5Bold: true;
    h5sRegular: true;
    h5sMedium: true;
    h5sSemiBold: true;
    h5sBold: true;
    h6Regular: true;
    h6Medium: true;
    h6SemiBold: true;
    h6Bold: true;
    h6sRegular: true;
    h6sMedium: true;
    h6sSemiBold: true;
    h6sBold: true;
    sRegular: true;
    sMedium: true;
    sSemiBold: true;
    sBold: true;
    p1Regular: true;
    p1Medium: true;
    p1SemiBold: true;
    p1Bold: true;
    p2Regular: true;
    p2Medium: true;
    p2SemiBold: true;
    p2Bold: true;
    p3Regular: true;
    p3Medium: true;
    p3SemiBold: true;
    p3Bold: true;
    captionRegular: true;
    captionMedium: true;
    captionSemiBold: true;
    captionBold: true;
    fRegular: true;
    fMedium: true;
    fSemiBold: true;
    fBold: true;
  }
}

const typography = {
  d1Regular: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    textShadow: "0px 4px 4px rgba(0, 0, 0, 0.25)",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "72px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "80px",
    letterSpacing: "-2.88px",
  },
  d1Medium: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "72px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "80px",
    letterSpacing: "-2.88px",
  },
  d1SemiBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    textShadow: "0px 4px 4px rgba(0, 0, 0, 0.25)",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "72px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "80px",
    letterSpacing: "-2.88px",
  },
  d1Bold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    textShadow: "0px 4px 4px rgba(0, 0, 0, 0.25)",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "72px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "80px",
    letterSpacing: "-2.88px",
  },
  d2Regular: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "60px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "72px",
    letterSpacing: "-2.4px",
  },
  d2Medium: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "60px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "72px",
    letterSpacing: "-2.4px",
  },
  d2SemiBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "60px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "72px",
    letterSpacing: "-2.4px",
  },
  d2Bold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "60px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "72px",
    letterSpacing: "-2.4px",
  },
  h1Regular: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "48px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "56px",
    letterSpacing: "-1.92px",
  },
  h1Medium: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "48px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "56px",
    letterSpacing: "-1.92px",
  },
  h1SemiBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "48px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "56px",
    letterSpacing: "-1.92px",
  },
  h1Bold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "48px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "56px",
    letterSpacing: "-1.92px",
  },
  h1sRegular: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "34px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "40px",
    letterSpacing: "-1.36px",
  },
  h1sMedium: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "34px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "40px",
    letterSpacing: "-1.36px",
  },
  h1sSemiBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "34px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "40px",
    letterSpacing: "-1.36px",
  },
  h1sBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "34px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "40px",
    letterSpacing: "-1.36px",
  },
  h2Regular: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "48px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "48px",
    letterSpacing: "-1.6px",
  },
  h2Medium: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "48px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "48px",
    letterSpacing: "-1.6px",
  },
  h2SemiBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "48px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "48px",
    letterSpacing: "-1.6px",
  },
  h2Bold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "48px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "48px",
    letterSpacing: "-1.6px",
  },
  h2sRegular: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "32px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "40px",
    letterSpacing: "-0.64px",
  },
  h2sMedium: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "32px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "40px",
    letterSpacing: "-0.64px",
  },
  h2sSemiBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "32px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "40px",
    letterSpacing: "-0.64px",
  },
  h2sBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "32px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "40px",
    letterSpacing: "-0.64px",
  },
  h3Regular: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "32px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "40px",
    letterSpacing: "-0.64px",
  },
  h3Medium: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "32px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "40px",
    letterSpacing: "-0.64px",
  },
  h3SemiBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "32px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "40px",
    letterSpacing: "-0.64px",
  },
  h3Bold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "32px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "40px",
    letterSpacing: "-0.64px",
  },
  h3sRegular: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "28px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "36px",
    letterSpacing: "-0.56px",
  },
  h3sMedium: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "28px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "36px",
    letterSpacing: "-0.56px",
  },
  h3sSemiBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "28px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "36px",
    letterSpacing: "-0.56px",
  },
  h3sBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "28px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "36px",
    letterSpacing: "-0.56px",
  },
  h4Regular: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "28px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "36px",
    letterSpacing: "-0.56px",
  },
  h4Medium: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "28px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "36px",
    letterSpacing: "-0.56px",
  },
  h4SemiBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "28px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "36px",
    letterSpacing: "-0.56px",
  },
  h4Bold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "28px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "36px",
    letterSpacing: "-0.56px",
  },
  h4sRegular: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "24px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "32px",
    letterSpacing: "-0.48px",
  },
  h4sMedium: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "24px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "32px",
    letterSpacing: "-0.48px",
  },
  h4sSemiBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "24px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "32px",
    letterSpacing: "-0.48px",
  },
  h4sBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "24px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "32px",
    letterSpacing: "-0.48px",
  },
  h5Regular: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "24px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "32px",
    letterSpacing: "-0.48px",
  },
  h5Medium: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "24px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "32px",
    letterSpacing: "-0.48px",
  },
  h5SemiBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "24px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "32px",
    letterSpacing: "-0.48px",
  },
  h5Bold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "24px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "32px",
    letterSpacing: "-0.48px",
  },
  h5sRegular: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "28px",
    letterSpacing: "-0.4px",
  },
  h5sMedium: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "28px",
    letterSpacing: "-0.4px",
  },
  h5sSemiBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "28px",
    letterSpacing: "-0.4px",
  },
  h5sBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "28px",
    letterSpacing: "-0.4px",
  },
  h6Regular: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "28px",
    letterSpacing: "-0.4px",
  },
  h6Medium: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "28px",
    letterSpacing: "-0.4px",
  },
  h6SemiBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "28px",
    letterSpacing: "-0.4px",
  },
  h6Bold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "28px",
    letterSpacing: "-0.4px",
  },
  h6sRegular: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "26px",
    letterSpacing: "-0.36px",
  },
  h6sMedium: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "26px",
    letterSpacing: "-0.36px",
  },
  h6sSemiBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "26px",
    letterSpacing: "-0.36px",
  },
  h6sBold: {
    color: "#091E42",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "26px",
    letterSpacing: "-0.36px",
  },
  sRegular: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "28px",
    letterSpacing: "-0.2px",
  },
  SMedium: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "28px",
    letterSpacing: "-0.2px",
  },
  sSemiBold: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "28px",
    letterSpacing: "-0.2px",
  },
  SBold: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "28px",
    letterSpacing: "-0.2px",
  },
  //////
  p1Regular: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "26px",
    letterSpacing: "-0.36px",
  },
  p1Medium: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "26px",
    letterSpacing: "-0.36px",
  },
  p1SemiBold: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "26px",
    letterSpacing: "-0.36px",
  },
  p1Bold: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "26px",
    letterSpacing: "-0.36px",
  },
  p2Regular: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "24px",
    letterSpacing: "-0.08px",
  },
  p2Medium: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "24px",
    letterSpacing: "-0.08px",
  },
  p2SemiBold: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "24px",
    letterSpacing: "-0.08px",
  },
  p2Bold: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "24px",
    letterSpacing: "-0.08px",
  },
  p3Regular: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "20px",
    letterSpacing: "-0.07px",
  },
  p3Medium: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "20px",
    letterSpacing: "-0.07px",
  },
  p3SemiBold: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "20px",
    letterSpacing: "-0.07px",
  },
  p3Bold: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "20px",
    letterSpacing: "-0.07px",
  },
  captionRegular: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "16px",
  },
  captionMedium: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "16px",
  },
  captionSemiBold: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "16px",
  },
  captionBold: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "16px",
    letterSpacing: "0.96px",
    textTransform: "uppercase",
  },

  fRegular: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "10px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "14px",
    letterSpacing: "-0.2px",
  },
  fMedium: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "10px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "14px",
    letterSpacing: "-0.2px",
  },
  fSemiBold: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "10px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "14px",
    letterSpacing: "-0.2px",
  },
  fBold: {
    color: "var(--neutral-gray-900, #0F172A)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Plus Jakarta Sans",
    fontSize: "10px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "14px",
    letterSpacing: "-0.2px",
  },
};

export default typography;
